### ISSUE TITLE
上拉加载,下拉刷新如何使用?

### ISSUE THREAD

**Issue by easywangzhe** [xuehuayous/DelegationAdapter#1]

**Comment by easywangzhe** [comment]
关于position,如何让每个delegate的position从0开始,而不是一直叠加,或者说有什么方法能获取到当前deletege的首个position?

**Comment by easywangzhe** [comment]
> 你可以查看Demo中的[RefreshLoadActivity](https://github.com/xuehuayous/DelegationAdapter/blob/master/sample/src/main/java/com/kevin/delegationadapter/sample/refreshload/RefreshLoadActivity.java)，在这个实例中使用的[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)，当然你可以自由选择。

关于position,如何让每个delegate的position从0开始,而不是一直叠加,或者说有什么方法能获取到当前deletege的首个position?

**Comment by xuehuayous** [comment]
设计的最初考虑的是数据驱动，不关注具体的位置、下标等，不过你可以说下具体的业务场景，我看下怎么优雅的解决这个问题。

**Comment by easywangzhe** [comment]
> 设计的最初考虑的是数据驱动，不关注具体的位置、下标等，不过你可以说下具体的业务场景，我看下怎么优雅的解决这个问题。

传集合数据的时候,例如demo中的BannerAdapterDelegate中那种样式,但是是出现在中间某个位置,还有会根据position的位置去动态的做一些设置等等
当然这些功能是可以做到的,这边可以调试出position的值,但是如果我的ui排序发送变化的时候,这些position值也要手动去改,就不太灵活.

**Comment by xuehuayous** [comment]
> 传集合数据的时候,例如demo中的BannerAdapterDelegate中那种样式,但是是出现在中间某个位置,还有会根据position的位置去动态的做一些设置等等
> 当然这些功能是可以做到的,这边可以调试出position的值,但是如果我的ui排序发送变化的时候,这些position值也要手动去改,就不太灵活.

不太明白你是怎么根据position的位置去动态设置的，可以详细说明下吗？

**Comment by easywangzhe** [comment]
> > 传集合数据的时候,例如demo中的BannerAdapterDelegate中那种样式,但是是出现在中间某个位置,还有会根据position的位置去动态的做一些设置等等
> > 当然这些功能是可以做到的,这边可以调试出position的值,但是如果我的ui排序发送变化的时候,这些position值也要手动去改,就不太灵活.
> 
> 不太明白你是怎么根据position的位置去动态设置的，可以详细说明下吗？

拿demo中的举个例子,demo中的BannerAdapterDelegate中有bannerView.setOnItemClickListener(new BaseLoopAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(View view, LoopData.ItemData itemData, int position) {
                Toast.makeText(view.getContext(), item.items.get(position).link, Toast.LENGTH_SHORT).show();
            }
        });
这里用到了position,因为传入了一个集合对象,这里position是正常的,因为banner是列表的第一个,position从0开始,但是如果有其他的delegate中也有这样的需求,但是是放在中间,这个时候拿到的position可能是6,7,这个时候使用positon从集合里面取出对应的值就出问题了

**Comment by xuehuayous** [comment]
> 拿demo中的举个例子,demo中的BannerAdapterDelegate中有bannerView.setOnItemClickListener(new BaseLoopAdapter.OnItemClickListener() {
> @override
> public void onItemClick(View view, LoopData.ItemData itemData, int position) {
> Toast.makeText(view.getContext(), item.items.get(position).link, Toast.LENGTH_SHORT).show();
> }
> });
> 这里用到了position,因为传入了一个集合对象,这里position是正常的,因为banner是列表的第一个,position从0开始,但是如果有其他的delegate中也有这样的需求,但是是放在中间,这个时候拿到的position可能是6,7,这个时候使用positon从集合里面取出对应的值就出问题了

这里如果换成数据驱动，就是点击了哪一个让内部把数据传递出来，就不会有位置、下标的问题，你的场景是不是也可以使用这种思路优化呢。
`
bannerView.setOnItemClickListener(new BaseLoopAdapter.OnItemClickListener() {
    @Override
    public void onItemClick(View view, LoopData.ItemData itemData, int position) {
//                Toast.makeText(view.getContext(), item.items.get(position).link, Toast.LENGTH_SHORT).show();
        Toast.makeText(view.getContext(), itemData.link, Toast.LENGTH_SHORT).show();
    }
});
`

**Comment by easywangzhe** [comment]
> > 拿demo中的举个例子,demo中的BannerAdapterDelegate中有bannerView.setOnItemClickListener(new BaseLoopAdapter.OnItemClickListener() {
> > @override
> > public void onItemClick(View view, LoopData.ItemData itemData, int position) {
> > Toast.makeText(view.getContext(), item.items.get(position).link, Toast.LENGTH_SHORT).show();
> > }
> > });
> > 这里用到了position,因为传入了一个集合对象,这里position是正常的,因为banner是列表的第一个,position从0开始,但是如果有其他的delegate中也有这样的需求,但是是放在中间,这个时候拿到的position可能是6,7,这个时候使用positon从集合里面取出对应的值就出问题了
> 
> 这里如果换成数据驱动，就是点击了哪一个让内部把数据传递出来，就不会有位置、下标的问题，你的场景是不是也可以使用这种思路优化呢。
> 
> ```
> bannerView.setOnItemClickListener(new BaseLoopAdapter.OnItemClickListener() {
>     @Override
>     public void onItemClick(View view, LoopData.ItemData itemData, int position) {
>         //  Toast.makeText(view.getContext(), item.items.get(position).link, Toast.LENGTH_SHORT).show();
>         Toast.makeText(view.getContext(), itemData.link, Toast.LENGTH_SHORT).show();
>     }
> });
> ```

这里是一种解决办法,但是不是涉及到数据问题,而是显示问题的时候,比如列表中间添加了一个deletegate,例如demo中的TagAdapterDelegate,我需要在这一排的中间也就是第三个,或者最后一个的时候去改变他的背景图,而这个时候的postion初始位置并不是从0开始的(可能是6,7,这里要看他所处列表的位置,)这个时候就我这边如果不事先确定好他的position的起始坐标就不好实现这个功能

**Comment by xuehuayous** [comment]
> 这里是一种解决办法,但是不是涉及到数据问题,而是显示问题的时候,比如列表中间添加了一个deletegate,例如demo中的TagAdapterDelegate,我需要在这一排的中间也就是第三个,或者最后一个的时候去改变他的背景图,而这个时候的postion初始位置并不是从0开始的(可能是6,7,这里要看他所处列表的位置,)这个时候就我这边如果不事先确定好他的position的起始坐标就不好实现这个功能

如果把一个数据在一组相同数据类型中的下标传递出来能否很好的解决你的问题呢？
例如：数据：4、"kevin"、"zhou"、 3、4.5F、7
当数据为4时，position=0，groupPosition=0
当数据为"kevin"时，position=1，groupPosition=0
当数据为"zhou"时，position=2，groupPosition=1
当数据为3时，position=3，groupPosition=0
```
@Override
protected void onBindViewHolder(ViewHolder holder, int position, int groupPosition, T item) {
}
```

**Comment by easywangzhe** [comment]
> 相同数据类型中的下标传递

这样应该是可以的,这边代码有更新吗,我去调试下?

**Comment by xuehuayous** [comment]
> > 相同数据类型中的下标传递
> 
> 这样应该是可以的,这边代码有更新吗,我去调试下?

本来我已经调整为这样，但是思来想去不太符合最初的数据驱动的想法，所以你还是使用其他方式实现吧。提供个思路，在添加数据的时候对数据进行标记。
