### ISSUE TITLE
您好，需求是运营配置页面结构后根据后端返回的数据app支持动态渲染，现在可以实现吗

### ISSUE THREAD

**Issue by matrixccp** [xuehuayous/DelegationAdapter#10]

**Comment by xuehuayous** [comment]
首先恭喜你，你们已经是APP界面功能导向而不是服务端业务导向的接口定义，`DelegationAdapter`理想应用场景就是这样的，当然可以满足你的需求。你可以参考[ChatActivity](https://github.com/xuehuayous/DelegationAdapter/blob/master/sample/src/main/java/com/kevin/delegationadapter/sample/multitype/chat/common/ChatActivity.java)里面处理不同类型条目的形式来进行开发。当然推荐你多看下demo中的各种应用场景以及整体的实现的原理。

**Comment by matrixccp** [comment]
> 首先恭喜你，你们已经是APP界面功能导向而不是服务端业务导向的接口定义，`DelegationAdapter`理想应用场景就是这样的，当然可以满足你的需求。你可以参考[ChatActivity](https://github.com/xuehuayous/DelegationAdapter/blob/master/sample/src/main/java/com/kevin/delegationadapter/sample/multitype/chat/common/ChatActivity.java)里面处理不同类型条目的形式来进行开发。当然推荐你多看下demo中的各种应用场景以及整体的实现的原理。

好的，谢谢，我试试看
