### ISSUE TITLE
可以把最新Release version 1.1.8代码合并到dev_java分支么

### ISSUE THREAD

**Issue by sheng930920** [xuehuayous/DelegationAdapter#11]
可以把最新Release version 1.1.8代码合并到dev_java分支么，想研究一下全部最新的Java代码

**Comment by xuehuayous** [comment]
项目最初使用Java代码开发的，随着Google官方对Kotlin大力支持，以及Kotlin的越来越流行，就使用Kotlin对项目进行了重构。但是核心部分的原理依旧和[`dev_java`](https://github.com/xuehuayous/DelegationAdapter/tree/dev_java)一致，只是在之前的基础上进行了部分问题的修复以及功能的扩展。相信你即便不太了解Koltin也能看懂它的，过程中也可以对Koltin有所了解。
