### ISSUE TITLE
关于局部刷新的问题

### ISSUE THREAD

**Issue by WnagYo** [xuehuayous/DelegationAdapter#12]
比如是一个论坛形式的页面，下面是评论区，评论区里面有选项可以选择最热，最新等选项，那么我如何只替换或者刷新下面这部分，调用notifyDataSetChanged()方法之后，页面会跑到最上面。有什么建议或者参考吗？

**Comment by xuehuayous** [comment]
上面部分使用`adapter.addHeaderItem`这种形式设置数据，下面部分使用`adapter.setDataItems`这种形式设置数据，这样就区分开了上下部分。

**Comment by WnagYo** [comment]
不好意思最近又去忙了其他的，没有及时反馈。
我看了一下 ``` 百度百聘 ``` ，跟我的情况不太一样。

我的页面如下图，上面的正文部分是``` header```，使用的是``` setHeaderItems```，中间还有自己回复的部分为 ``` setDataItems```，下面别人的评论是 ``` setFooterItems```。当用户点击最早或者最新按钮的时候，使用的是``` setFooterItems```设置数据，这时候就会出现两种情况。

第一种，当头部显示的时候，点击最早或者最新按钮，页面会跑到最上面。

![image](https://user-images.githubusercontent.com/29337191/61345391-7fd18680-a887-11e9-801d-8c7758e2331a.png)


第二种，当头部已经划出屏幕外，点击最早或者最新按钮，界面则不会发生变化。像下面图片的这种情况。

![image](https://user-images.githubusercontent.com/29337191/61345398-895aee80-a887-11e9-8c3f-8b24b8a6a992.png)

**Comment by WnagYo** [comment]
Thank you.
