### ISSUE TITLE
数据源不一样的时候?

### ISSUE THREAD

**Issue by open9527** [xuehuayous/DelegationAdapter#13]
当主界面的数据源不是一个对象返回的时候,这个数据源就不一样的,如果不去组装这个数据集合的话,有没有好的方式去处理了

**Comment by xuehuayous** [comment]
可以通过`addHeaderItem` `addFooterItem`向指定头部或尾部添加数据，`addDataItem`向指定中间位置添加数据，前提是你要知道应该往什么位置插入数据。

**Comment by open9527** [comment]
没理解在代理适配器中getItemViewType 是依据什么区分配的

**Comment by xuehuayous** [comment]
在定义`AdapterDelegate`时，泛型内的T就是当前AdapterDelegate能处理的数据类型。
```
public class CompanyAdapterDelegate extends AdapterDelegate<String, CompanyAdapterDelegate.ViewHolder> 
```
在`addDelegate()`的时候会读取该泛型，并内部维护T → `itemViewType`的映射，`getItemViewType()`时根据当前`item`的类型去查找匹配的`itemViewType`。
