### ISSUE TITLE
你好，请教一下关于刷新的场景问题

### ISSUE THREAD

**Issue by jack60** [xuehuayous/DelegationAdapter#17]
楼主你好，现在我有一个这样的需求
![image](https://user-images.githubusercontent.com/15207166/81781909-88d4c800-952b-11ea-8b38-68a5e7c36c07.png)

1.这个是后台网页拖拽控件，然后移动端生成对应的控件，我想用大佬的这个框架，但是我要刷新指定的某个item，要怎么刷新，比如我现在加了头部 获取到的position的位置就不准了，更新不了集合的数据。比如现在有个item ，点击这个item 要跳到另外一个activity  选择数据，回到当前activity 显示刚刚选择的数据，怎么去记录点击的item的下标。

2.还有一种这种情况， 比如item 里面还有一个子item 我点击子item的一个button按钮 要调起选择图片，对应的activity  要在onActivityResult 监听选择图片的返回，然后图片显示对应的子item 上面， 要怎么把当前点击的item 的子item 的坐标传回activity 让他记录点击的哪一个下标，好更新对应的数据，   不知道我表达的清楚没

还有一点  我感觉这个框架 好像对应纯展示列表的数据，是很好的实现很方便，  但是要增删改查就有点不太好搞了。

**Comment by xuehuayous** [comment]
1. 更新数据可以使用`delegationAdapter.updateDataItem(item)`进行刷新指定数据的条目；
2. 是不是可以通过在创建条目委托的时候将activity传递进去`delegationAdapter.addDelegate(ItemDelegate(activity))`，这样在操作的时候可以把当前的条目对于的数据传递给activity，在onActivityResult回来的时候更新条目数据就可以了，然后`delegationAdapter.updateDataItem(item)`。

在设计之初就是考虑的数据驱动界面显示，所有的操作都要以操作数据，然后数据更新显示。

**Comment by jack60** [comment]
1.我用的是java 版的没有delegationAdapter.updateDataItem(item) ， 我换到最新的是有delegationAdapter.updateDataItem(item) 但是调用这个方法 list<String> 里面是String 的时候刷新不了
![image](https://user-images.githubusercontent.com/15207166/82639967-50746e80-9c3c-11ea-9643-d7739a70f7c8.png) 这里我改变了list集合String的值他们就不相等了就不会刷新， 对象是没问题的 这里应该是比地址。String 比的是值。 还有我刷新了数据有点重叠显示的样子，我直接用的你的demo修改的
![image](https://user-images.githubusercontent.com/15207166/82640516-5454c080-9c3d-11ea-8a13-2125256ba9d6.png)

2.是不是可以通过在创建条目委托的时候将activity传递进去delegationAdapter.addDelegate(ItemDelegate(activity))  只有这种解决方案吗？ 这样耦合性有点高，如果其他类也要用到这个创建条目委托类的时候 ,不同的activity 就用不了了。

**Comment by jack60** [comment]
1.我用的是java 版的没有delegationAdapter.updateDataItem(item) ， 我换到最新的是有delegationAdapter.updateDataItem(item) 但是调用这个方法 list 里面是String 的时候刷新不了
  
@JvmOverloads
    fun updateDataItem(dataItem: Any?, tag: String = AdapterDelegate.DEFAULT_TAG) {
        if (dataItem == null) {
            return
        }

        dataItems.forEachIndexed { index, item ->
            if (item is ItemData && dataItem == item.data && tag == item.tag) {
                notifyItemChanged(headerCount + index)
            } else if (dataItem == item) {
                notifyItemChanged(headerCount + index)
            }
        }
    }

 if (dataItem == item) 这里我改变了list集合String的值他们就不相等了就不会刷新， 对象是没问题的 这里应该是比地址。String 比的是值。 还有我刷新了数据有点重叠显示的样子，我直接用的你的demo修改的
![image](https://user-images.githubusercontent.com/15207166/82642038-d9d97000-9c3f-11ea-9089-92079feb9c07.png)


2.是不是可以通过在创建条目委托的时候将activity传递进去delegationAdapter.addDelegate(ItemDelegate(activity)) 只有这种解决方案吗？ 这样耦合性有点高，如果其他类也要用到这个创建条目委托类的时候 ,不同的activity 就用不了了。

**Comment by jack60** [comment]
你好  这个支持List<List<对象>>  这样的数据结构吗？ 现在好像只支持List<对象>  这样的数据委托给条目

**Comment by xuehuayous** [comment]
暂不支持
