### ISSUE TITLE
列表分组的情况这个可以处理吗

### ISSUE THREAD

**Issue by easywangzhe** [xuehuayous/DelegationAdapter#2]
列表分成了多个组,每组含有相同样式的标题,
多次使用delegationAdapter.addHeaderItem,
delegationAdapter.addDataItems()发现无法分组,列表中的内容会集中在一起

**Comment by xuehuayous** [comment]
标题通过`delegationAdapter.addDataItem()`，列表数据通过`delegationAdapter.addDataItems()`就可以了。
