### ISSUE TITLE
SameDataActivityBinding   在哪定义的呢

### ISSUE THREAD

**Issue by ObliverSen** [xuehuayous/DelegationAdapter#6]
public class SameDataActivity extends AppCompatActivity {

    SameDataActivityBinding mBinding;
   //SameDataActivityBinding     怎么来的啊 ？？

**Comment by xuehuayous** [comment]
使用databinding技术通过编译时生成代码生成的，你可以看到在`activity_same_data.xml`中定义了
```
    <data class=".samedata.SameDataActivityBinding">
    </data>
```
关于databinding你可以参考我的博客[《认识Android中的双向绑定》](https://blog.csdn.net/xuehuayous/article/details/81100571)、[《Android中MVVM是什么？》](https://blog.csdn.net/xuehuayous/article/details/82777022) 或者网上的其他资源及官方文档。
