### ISSUE TITLE
AdapterDelegate点击事件怎么处理

### ISSUE THREAD

**Issue by whao77** [xuehuayous/DelegationAdapter#8]
item和item子控件的点击事件怎么处理呢

**Comment by xuehuayous** [comment]
item的点击事件可以继承`ClickableAdapterDelegate`，提供了`onItemClick`方法，item子控件的点击事件可以在`onCreateViewHolder`中进行自己设置监听。当然item的点击也可以在`onCreateViewHolder`中进行自己设置监听。
