### ISSUE TITLE
参考BRVAH后，关于折叠式的adapter如何处理？

### ISSUE THREAD

**Issue by CJEEP** [xuehuayous/DelegationAdapter#9]
你好，DelegationAdapter库的开发者，我冒昧想请教一下，用委托adapter如何实现跟BRVAH库 里面的功能，比如折叠adapter 和拖拽adapter这个？

**Comment by xuehuayous** [comment]
不好意思，我之前没有了解过`BRVAH`，我周末了解下，之后再回复你吧。

**Comment by xuehuayous** [comment]
拖拽排序你可以参考下项目的[`HomeActivity`](https://github.com/xuehuayous/DelegationAdapter/blob/master/sample/src/main/java/com/kevin/delegationadapter/sample/home/HomeActivity.java)其实还是RecyclerView提供的拖拽帮助类，只是为了方便控制`DelegationAdapter`提供了`swapDataItem`的方法。请使用最新版本，另外折叠的我后续有时间就看下，最近996，比较忙。
